[tools]
rojo = { source = "roblox/rojo", version = "7.0.0" }
# run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.17.0" }